[build]
  publish = "."

[[headers]]
  for = "/*.pdf"
  [headers.values]
    Content-Type = "application/pdf"

[[headers]]
  for = "/assets/*.pdf"
  [headers.values]
    Content-Type = "application/pdf"
